name: ColorBlocks
version: '${project.version}'
main: org.untitleda.colorblocks.ColorBlocks
api-version: 1.19
author: Vauxten
website: colorblocks.vauxten.repl.co
description: Main plugin for ColorBlocks.
commands:
  colorblocks:
    description: Good try.
    usage: /<command>
    aliases: /cb
  newgame:
    description: Creates a new game.
    usage: /<command>
    aliases: /ngame